# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4d83e7af142fc874991f0f706dd26d06350abb96b29b46d2cde0710903d8fcfe3ad1c906b56f59234690201fc8f1004ef2f91be511846735b102dd03f45723

test:
  secret_key_base: fb6d4421d131abe5c166a83682304ffae2a12cfa9ad391aac6c9aa500fcbd46682bab4f85be320eb642f000e1d022b73ecf428bafee5b8fd80b66b6fd90b4371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
